### PR TITLE
add tryTake function

### PR DESCRIPTION
**Pull request by lust4life**
- use `MVar` to simulate the buffer state (full/empty)
   seems using `mvar` as the state can avoid a round-trip between client and server.
- add `tryTake` function

### CODE REVIEW

**Comment by haf** [comment]
@lust4life Great to see you again! :)

Two questions:

 1. Are you sure your extra closure allocations in tryTake https://github.com/logary/RingBuffer/pull/4/files#diff-0e73d3207a9e5a8731b842102e2282c7R75 don't end up eating more GC/speed than the check of the promise?
 2. I think `tryTake: q -> Alt<'a option>` is a better signature than `tryTake: q -> Alt<bool * 'a>`, since it's primarily in interop with C#-scenarios that `TryTake` is to return a bool and a possibly-undefined value. In F# it's preferred to return an option.

**Comment by lust4life** [comment]
@haf  😺   

1. promise can be filled only once, I think `mvar` here is more suitable. 
2. got it, you are right. 

will add more benchmark test later

**Comment by haf** [comment]
I think your tests need updating too.

Can you please add tests on the empty/full mvars too? Their state after 1) initially empty, 2) first full, 3) not full not empty, 4) second empty, 4) second full?

**Comment by lust4life** [comment]
@haf  tests updated and added some benchmark:
```
// * Detailed results *
Ring.tryPutChannel: DefaultJob
Runtime = .NET Core 2.1.4 (CoreCLR 4.6.26814.03, CoreFX 4.6.26814.02), 64bit RyuJIT; GC = Concurrent Workstation
Mean = 386.2632 ms, StdErr = 2.1641 ms (0.56%); N = 20, StdDev = 9.6780 ms
Min = 376.4782 ms, Q1 = 380.0593 ms, Median = 384.5299 ms, Q3 = 388.1829 ms, Max = 415.9984 ms
IQR = 8.1236 ms, LowerFence = 367.8740 ms, UpperFence = 400.3683 ms
ConfidenceInterval = [377.8592 ms; 394.6672 ms] (CI 99.9%), Margin = 8.4040 ms (2.18% of Mean)
Skewness = 1.61, Kurtosis = 5.15, MValue = 2
-------------------- Histogram --------------------
[375.507 ms ; 390.494 ms) | @@@@@@@@@@@@@@@@@
[390.494 ms ; 404.909 ms) | @@
[404.909 ms ; 419.118 ms) | @
---------------------------------------------------

Ring.tryPutMVar: DefaultJob
Runtime = .NET Core 2.1.4 (CoreCLR 4.6.26814.03, CoreFX 4.6.26814.02), 64bit RyuJIT; GC = Concurrent Workstation
Mean = 149.2545 ms, StdErr = 0.7488 ms (0.50%); N = 18, StdDev = 3.1770 ms
Min = 145.2451 ms, Q1 = 146.1996 ms, Median = 149.3578 ms, Q3 = 150.8530 ms, Max = 155.5590 ms
IQR = 4.6534 ms, LowerFence = 139.2195 ms, UpperFence = 157.8331 ms
ConfidenceInterval = [146.2853 ms; 152.2237 ms] (CI 99.9%), Margin = 2.9692 ms (1.99% of Mean)
Skewness = 0.38, Kurtosis = 1.92, MValue = 2
-------------------- Histogram --------------------
[144.184 ms ; 147.192 ms) | @@@@@@
[147.192 ms ; 151.542 ms) | @@@@@@@@
[151.542 ms ; 156.051 ms) | @@@@
---------------------------------------------------

Total time: 00:04:31 (272 sec)

// * Summary *

BenchmarkDotNet=v0.10.14, OS=macOS 10.14 (18A391) [Darwin 18.0.0]
Intel Core i5-7500 CPU 3.40GHz (Kaby Lake), 1 CPU, 4 logical and 4 physical cores
.NET Core SDK=2.1.402
  [Host]     : .NET Core 2.1.4 (CoreCLR 4.6.26814.03, CoreFX 4.6.26814.02), 64bit RyuJIT DEBUG
  DefaultJob : .NET Core 2.1.4 (CoreCLR 4.6.26814.03, CoreFX 4.6.26814.02), 64bit RyuJIT


        Method |     Mean |    Error |   StdDev |
-------------- |---------:|---------:|---------:|
 tryPutChannel | 386.3 ms | 8.404 ms | 9.678 ms |
 tryPutMVar    | 149.3 ms | 2.969 ms | 3.177 ms |
```

**Comment by haf** [comment]
Thank you @lust4life!

**Pull request merged**
